// OWNER: Agent B (Kaustubh). Auto-generated post-incident report. Rendered inside the
// shared drawer shell when activeDrawer === 'report'.
import { Download, Printer } from 'lucide-react';
import { useStore, useMakegoodTotals } from '../../core/store';
import { SCENARIOS } from '../../core/scenarios';
import { fmtPct, fmtT, fmtUSD } from '../../core/format';
import type { Channel, LogEntry } from '../../core/types';

const CHANNEL_LABEL: Record<Channel, string> = { status_page: 'Status page', push: 'Push', email: 'Email', x_post: 'Post on X' };
const ACTOR_LABEL: Record<LogEntry['actor'], string> = { system: 'System', responder: 'Responder', human: 'Human' };

function Fact({ label, value, accent = 'text-ink' }: { label: string; value: string; accent?: string }) {
  return (
    <div className="flex items-baseline justify-between gap-3 border-b border-line/60 py-1.5 text-sm">
      <span className="text-muted">{label}</span>
      <span className={`num font-semibold ${accent}`}>{value}</span>
    </div>
  );
}

export function ReportDrawer() {
  const s = useStore();
  const { count: makegoodCount, total: totalOwed } = useMakegoodTotals();
  const meta = SCENARIOS[s.scenario];
  const noMakegood = s.liquidations.filter((l) => l.verdict === 'no_makegood').length;
  const pending = s.liquidations.filter((l) => l.verdict === 'pending').length;
  const paid = s.liquidations.filter((l) => l.status === 'paid');
  const paidTotal = s.reserveStart - s.reserveBalance;
  const sent = s.comms.filter((c) => c.status === 'sent');
  const started = s.phase !== 'setup';
  const complete = s.phase === 'ended';

  const facts: [string, string][] = [
    ['Scenario', meta.label],
    ['Report as of', started ? fmtT(s.simTime) : 'Not started'],
    ['Deviation band (locked)', `±${fmtPct(s.bandPct)}`],
    ['Human calls used', `${s.humanCallsUsed} / 1`],
    ['Liquidations', String(s.liquidations.length)],
    ['Makegoods owed', String(makegoodCount)],
    ['Within band (no makegood)', String(noMakegood)],
    ['Awaiting deviation test', String(pending)],
    ['Total owed', fmtUSD(totalOwed)],
    ['Paid so far', `${fmtUSD(paidTotal)} (${paid.length} users)`],
    ['Integrity Reserve before', fmtUSD(s.reserveStart)],
    ['Integrity Reserve after', fmtUSD(s.reserveBalance)],
  ];

  const toMarkdown = () => {
    const lines = [
      `# Post-incident report: MochaTrade`,
      '',
      `Generated by the Dead-Hand Console${complete ? '' : ` (incident still in progress at ${fmtT(s.simTime)})`}.`,
      '',
      '## Summary',
      '',
      ...facts.map(([k, v]) => `- **${k}:** ${v}`),
      '',
      '## Verdict',
      '',
      makegoodCount > 0
        ? `Our price was wrong for ${makegoodCount} users (more than ${fmtPct(s.bandPct)} from the reference median). We owe ${fmtUSD(totalOwed)}, paid from the Integrity Reserve.`
        : pending > 0 || !started
          ? 'Deviation test not yet complete.'
          : `All executions were within the ${fmtPct(s.bandPct)} band. The market moved; our price did not. No makegoods owed.`,
      '',
      '## Timeline',
      '',
      ...s.log.map((e) => `- **${fmtT(e.t)}** · ${ACTOR_LABEL[e.actor]} · ${e.stage.toUpperCase()}: ${e.text}`),
      '',
      '## Communications sent',
      '',
      ...sent.map((c) => `- **${fmtT(c.t)}** · ${CHANNEL_LABEL[c.channel]}: ${c.title}\n\n  ${c.body.replace(/\n+/g, ' ')}`),
      '',
      '> "We pay when our price was wrong. We never pay because the market was."',
      '',
    ];
    return lines.join('\n');
  };

  const download = () => {
    const blob = new Blob([toMarkdown()], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mochatrade-incident-report-${s.scenario}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div data-print-root className="space-y-6">
      <div className="flex gap-2 print:hidden">
        <button
          type="button"
          onClick={download}
          className="inline-flex items-center gap-2 rounded-lg border border-cyan/50 bg-cyan/10 px-3.5 py-2 text-sm font-medium text-cyan hover:bg-cyan/15"
        >
          <Download size={15} /> Download report (.md)
        </button>
        <button
          type="button"
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 rounded-lg border border-line px-3.5 py-2 text-sm font-medium text-ink hover:border-cyan/40"
        >
          <Printer size={15} /> Print
        </button>
        {!complete && started && <span className="self-center text-xs text-muted">Incident in progress; report updates live.</span>}
      </div>

      <header>
        <h3 className="text-xl font-semibold text-ink">Post-incident report: MochaTrade</h3>
        <p className="text-xs text-muted">{meta.label} · Dead-Hand Protocol</p>
      </header>

      <section>
        <h4 className="mb-1 text-sm font-semibold tracking-wider text-muted uppercase">Summary</h4>
        <div className="grid grid-cols-2 gap-x-8">
          {facts.map(([k, v]) => (
            <Fact key={k} label={k} value={v} accent={k === 'Makegoods owed' && makegoodCount > 0 ? 'text-orange' : 'text-ink'} />
          ))}
        </div>
      </section>

      <section>
        <h4 className="mb-2 text-sm font-semibold tracking-wider text-muted uppercase">Timeline</h4>
        {s.log.length === 0 ? (
          <p className="text-sm text-muted">Nothing yet. Start a scenario.</p>
        ) : (
          <ol className="space-y-1.5">
            {s.log.map((e) => (
              <li
                key={e.id}
                className={`grid grid-cols-[64px_84px_1fr] gap-3 rounded-md px-2 py-1.5 text-xs ${e.actor === 'human' ? 'border border-orange/40 bg-orange/10' : 'bg-surface-2/40'}`}
              >
                <span className="num text-cyan">{fmtT(e.t)}</span>
                <span className={`font-semibold uppercase ${e.actor === 'human' ? 'text-orange' : 'text-muted'}`}>{ACTOR_LABEL[e.actor]}</span>
                <span className="text-ink/90">{e.text}</span>
              </li>
            ))}
          </ol>
        )}
      </section>

      <section>
        <h4 className="mb-2 text-sm font-semibold tracking-wider text-muted uppercase">Communications sent</h4>
        {sent.length === 0 ? (
          <p className="text-sm text-muted">None yet.</p>
        ) : (
          <ol className="space-y-2">
            {sent.map((c) => (
              <li key={c.id} className="rounded-md border border-line px-3 py-2 text-xs">
                <div className="flex justify-between text-muted">
                  <span>{CHANNEL_LABEL[c.channel]}</span>
                  <span className="num">{fmtT(c.t)}</span>
                </div>
                <div className="mt-0.5 font-semibold text-ink">{c.title}</div>
                <p className="mt-0.5 whitespace-pre-line text-ink/80">{c.body}</p>
              </li>
            ))}
          </ol>
        )}
      </section>
    </div>
  );
}
