// Frozen store snapshot at T+35:00 of the system_fault scenario, for building panels
// before the engine is wired in. Load it with ?fixture=1 in the URL.
//
// It is generated by the real engine, so it always matches what a live run shows.
// Makegoods are queued but NOT confirmed, so "Confirm makegoods" can be tested.
// Press Resume to continue the run from T+35:00.
import type { SimState } from './types';
import { advance, createInitialState } from './engine';

export const FIXTURE_TIME = 35 * 60;

export function buildFixture(): SimState {
  const start = advance({ ...createInitialState('system_fault'), phase: 'running', bandLocked: true }, 0);
  return { ...advance(start, FIXTURE_TIME), phase: 'paused' };
}

export function fixtureRequested(): boolean {
  return typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('fixture') === '1';
}
